version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgresql_db
      POSTGRES_USER: yuuki
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: